### ISSUE TITLE
We need to add a json validator 

### ISSUE THREAD

**Issue by TrevKnows** [adafruit/pyleap.github.io#1]
Heya - you mentioned in our meeting that you wrote a validator for a different program and that you'll commit it when you have the chance.

**Comment by ladyada** [comment]
@TrevKnows i think the schema.json was something ya tried with the validator? for now i removed it.

**Comment by ladyada** [comment]
simple validator added

https://github.com/adafruit/pyleap.github.io/blob/gh-pages/.github/testjson.py

@TrevKnows @tannewt take a look

**Comment by TrevKnows** [comment]
Looks good!
